apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kagent-tools:kagent.dev/ModelConfig:default/vllm-gpt
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kagent.dev/v1alpha2","kind":"ModelConfig","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kagent-tools:kagent.dev/ModelConfig:default/vllm-gpt"},"labels":{"app.kubernetes.io/component":"vllm-gpt","app.kubernetes.io/instance":"kagent-tools","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"vllm-gpt","helm.sh/chart":"mcp-tools-0.2.0"},"name":"vllm-gpt","namespace":"default"},"spec":{"apiKeySecret":"vllm-dummy-key","apiKeySecretKey":"OPENAI_API_KEY","model":"/data/gpt-oss-20b","openAI":{"baseUrl":"http://vllm-llama3-engine-service/v1"},"provider":"OpenAI"}}
  creationTimestamp: "2026-02-01T13:34:37Z"
  generation: 9
  labels:
    app.kubernetes.io/component: vllm-gpt
    app.kubernetes.io/instance: kagent-tools
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vllm-gpt
    helm.sh/chart: mcp-tools-0.2.0
  name: vllm-gpt
  namespace: default
  resourceVersion: "105785591"
  uid: 4982d7aa-55e4-49c8-8bdb-6fb358880d93
spec:
  apiKeySecret: vllm-dummy-key
  apiKeySecretKey: OPENAI_API_KEY
  model: /data/gpt-oss-20b
  openAI:
    baseUrl: http://vllm-llama3-engine-service/v1
  provider: OpenAI
status:
  conditions:
  - lastTransitionTime: "2026-02-01T13:34:37Z"
    message: Model configuration accepted
    reason: ModelConfigReconciled
    status: "True"
    type: Accepted
  observedGeneration: 9
  secretHash: dbe4d864db744d7009d4b63e101d4727ef369523de828ebf217b6ab54f881c8c
