apiVersion: v1
kind: Pod
metadata:
  name: model1-loader
spec:
  restartPolicy: Never
  containers:
    - name: loader
      image: docker.io/ronbutbul135/ubuntu:22.04
      command:
        - "sleep"
        - "infinity"
      volumeMounts:
        - name: model-storage
          mountPath: /data
  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: vllm-llama3-storage-claim
