apiVersion: v1
kind: Pod
metadata:
  name: node-debdugg
  namespace: default
spec:
  hostPID: true
  hostNetwork: true
  nodeName: i-00a15f289e0ecae20  # <-- CHANGE to your GPU node name
  containers:
    - name: debug
      image: ronbutbul135/alpine:3.19
      command:
        - sleep
        - infinity
      securityContext:
        privileged: true
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
