
singleNamespace: true
workflow:
  serviceAccount:
    create: true
    name: argo-workflow

  rbac:
    create: true
    serviceAccounts:
      - name: argo-workflow
        namespace: argo-workflow

controller:
  workflowDefaults:
    spec:
      serviceAccountName: argo-workflow


server:
  authModes:
    - server
  serviceType: ClusterIP

  secure: false

  ingress:
    enabled: true

    ingressClassName: nginx

    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    hosts:
      - argoworkflows.testmpr.aws2.rafael.co.il

    paths:
      - /

    pathType: Prefix

    tls:
      - secretName: testmpr-aws-wildcard-cert
        hosts:
          - argoworkflows.testmpr.aws2.rafael.co.il

images:
  pullPolicy: IfNotPresent


extraObjects:

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: argo-workflow-cluster-admin
    rules:
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - "*"

      - nonResourceURLs:
          - "*"
        verbs:
          - "*"

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: argo-workflow-cluster-admin
    subjects:
      - kind: ServiceAccount
        name: argo-workflow
        namespace: argo-workflow
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: argo-workflow-cluster-admin